Check Rebase added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,6 +6,30 @@ on:
       - 'rc_*'  # Adjust this pattern to match your rc_ branch naming convention
   
 jobs:
+  # ... (your existing jobs for commit message and keyword checks)
+
+  check-rebase:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0 # fetch the entire history
+
+    - name: Check for rebase
+      run: |
+        BASE_BRANCH=${{ github.event.pull_request.base.ref }} # Gets the base branch of the PR
+        git fetch origin $BASE_BRANCH                         # Fetch the base branch
+        COMMON_BASE=$(git merge-base $BASE_BRANCH HEAD)
+        LATEST_BASE_COMMIT=$(git rev-parse $BASE_BRANCH)
+        if [[ "$COMMON_BASE" == "$LATEST_BASE_COMMIT" ]]; then
+          echo "Feature branch is up to date with $BASE_BRANCH."
+        else
+          echo "Feature branch is not rebased on top of $BASE_BRANCH. Attempting to rebase..."
+          git rebase $BASE_BRANCH || (echo "Failed to rebase. Please rebase manually." && exit 1)
+        fi
+      
   build:
     runs-on: ubuntu-latest
     permissions:
@@ -14,3 +38,4 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+    
